version: '3.9'

services:
  soundness:
    container_name: ubuntu
    build:
      context: ./
      dockerfile: Dockerfile
    command: tail -f /var/log/lastlog
    volumes:
      - ./genkey.sh:/genkey.sh
    restart: always